---
abstract: 'Parse a traditional Changes file (as ADAMK interpretes it)'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Changes::ADAMK
name: Module-Changes-ADAMK
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0.4501
  DateTime::Format::CLDR: 1.06
  DateTime::Format::DateParse: 0.04
  Object::Tiny: 1.03
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Module-Changes-ADAMK
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Module-Changes-ADAMK
version: 0.11
